//tealium universal tag - utag.497 ut4.0.201906271117, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
function gtagEventCount(sendTo){gtag('event','conversion',{'allow_custom_scripts':true,'send_to':'DC-4522553/Corpo0/'+sendTo});}
function gtagEventLanguage(sendTo){var idioma=utag_data['page.lang'];if(document.location.pathname.search(/meetings\/blog/i)>-1){idioma='';if(document.domain.split('.')[2]=='es')idioma='spanish';else if(document.domain.split('.')[2]=='de')idioma='german';else if(document.domain.split('.')[2]=='com')idioma='english';else idioma='unknown';}
gtag('event','conversion',{'allow_custom_scripts':true,'u16':idioma,'send_to':'DC-4522553/Corpo0/'+sendTo});}
if(document.location.pathname.search(/booking\/confirmation/ig)==-1){var tckScript=document.createElement('script');tckScript.type='text/javascript';tckScript.async=true;tckScript.src='https://www.googletagmanager.com/gtag/js?id=AW-1044818160';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(tckScript,s);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1044818160');gtag('config','HA-222',{'conversion_cookie_prefix ':'_ha'});gtag('config','DC-4522553');}
var estadoAnterior=estadoAnterior||'not_logged';if(document.location.pathname.search(/newsletter/ig)>-1)gtagEventLanguage('nh_co001+standard');else if(document.location.pathname.search(/(business-travel|empresas|geschaeftsreisen|companies(program)?|entreprises)/ig)>-1)gtagEventLanguage('nh_em0+standard');else if(utag.data.page&&utag.data.page.section=='Destinations')gtagEventLanguage('nh_ag00+standard');else if(document.location.pathname=='/')gtagEventLanguage('NH_Ho0+standard');else if(document.location.pathname=='/meetings')gtagEventLanguage('nh_ev0+standard');else if(document.location.href.search(/nh-hotel.?s\.([a-z]{2,3})\/meetings\/blog/i)>-1)gtagEventLanguage('nh_co0+standard');else if(document.location.href.search(/nh-hotel.?s\.([a-z]{2,3})\/(booking\/)?meetings\/hotel/i)>-1)gtagEventLanguage('nh_mi0+standard');else if(document.location.href.search(/nh-hotel.?s\.([a-z]{2,3})\/booking\/meetings\/(organize|personalized)/i)>-1)gtagEventLanguage('nh_ev00+standard');else if(document.location.href.search(/nh-hotel.?s\.([a-z]{2,3})\/booking\/meetings\/confirmation/i)>-1)gtagEventLanguage('nh_ev000+standard');else if(document.location.pathname.search(/(deals|ofertas|angebote|aanbiedingen|offres|promocoes)/ig)>-1)gtagEventLanguage('nh_co000+standard');else if(document.location.pathname.search(/(agencias|travel\-agents|agenturen|agenzie|agences)/ig)>-1)gtagEventLanguage('nh_ag0+standard');else if(document.location.pathname.search(/yourspace/ig)>-1)gtagEventLanguage('event000+standard');else if(document.location.href.search(/nh-hotels\.biz\/(bpc|ys)\/[a-z]{2}\/success/i)>-1)gtagEventCount('event001+standard');if(utag.data.user.LoginState=='logged'&&estadoAnterior!=utag.data.user.LoginState&&utag.data.user.Profile=='rewards')gtagEventLanguage('nh_co00+standard');estadoAnterior=utag.data.user.LoginState;function gtagEventTwoParams(sendTo){gtag('event','conversion',{'allow_custom_scripts':true,'u16':b['idioma'],'u5':b['tckCiudad'].toLowerCase(),'send_to':'DC-4522553/Corpo0/'+sendTo});}
function gtagEventHPageParams(sendTo){gtag('event','conversion',{'allow_custom_scripts':true,'u16':b['idioma'],'u4':b['tckNombreHotel'].toLowerCase(),'u5':b['tckCiudad'].toLowerCase(),'u7':utag.data.products_id[0],'send_to':'DC-4522553/Corpo0/'+sendTo});}
var checkIn=b['qp.fini'];var checkOut=b['qp.fout'];if(document.location.pathname.search(/booking\/step1/i)>-1){setCookie('tckFini',checkIn);setCookie('tckFout',checkOut);}
function gtagEventHResultsParams(sendTo){var ciudad='';if(utag.data.page.section.search(/Search results/i)>-1)ciudad=b['busqCiudad'].toLowerCase();else ciudad=b['citySEO'].toLowerCase();gtag('event','conversion',{'allow_custom_scripts':true,'u16':b['idioma'],'u5':ciudad,'u1':checkIn,'u2':checkOut,'send_to':'DC-4522553/Corpo0/'+sendTo});}
function gtagEventSixParams(sendTo){gtag('event','conversion',{'allow_custom_scripts':true,'u16':b['idioma'],'u4':b['tckNombreHotel'].toLowerCase(),'u5':b['tckCiudad'].toLowerCase(),'u7':utag.data.products_id[0],'u1':checkIn,'u2':checkOut,'send_to':'DC-4522553/Corpo0/'+sendTo});}
function gtagSales(sendTo,kids,weekend,marcaDominio){var tckScript=document.createElement('script');tckScript.type='text/javascript';tckScript.async=true;tckScript.src='https://www.googletagmanager.com/gtag/js?id=AW-1044818160';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(tckScript,s);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1044818160');gtag('config','HA-222',{'conversion_cookie_prefix ':'_ha'});gtag('config','DC-4522553');var fini=getCookie('tckFini');var fout=getCookie('tckFout');gtag('event','purchase',{'allow_custom_scripts':true,'value':utag_data.resProd.split(";")[3],'transaction_id':utag_data.resId,'u1':fini,'u15':weekend,'u16':utag_data.idioma,'u17':utag_data['booking.roomnights'],'u2':fout,'u3':marcaDominio,'u4':b['tckNombreHotel'].toLowerCase(),'u5':b['tckCiudad'].toLowerCase(),'u6':b['tckPais'].toLowerCase(),'u7':utag_data.products_id[0],'u8':kids,'send_to':'DC-4522553/Sales0/'+sendTo});document.cookie='tckFini=;expires=Thu, 01 Jan 1970 00:00:01 GMT;';document.cookie='tckFout=;expires=Thu, 01 Jan 1970 00:00:01 GMT;';}
if(document.location.pathname.search(/hotel\/nh/ig)>-1)gtagEventHPageParams('NH_Fi0+standard');if(utag.data.page.section.search(/Search results/i)>-1)gtagEventHResultsParams('NH_Re0+standard');else if(document.location.pathname.search(/step1/ig)>-1)gtagEventSixParams('nh_co002+standard');else if(document.location.pathname.search(/step2/ig)>-1)gtagEventSixParams('nh_em00+standard');else if(document.location.pathname.search(/confirmation/ig)>-1){if(document.domain){marcaDominio=document.domain.split('.')[1];if(marcaDominio=='nh-hoteles'){marcaDominio='nh-hotels';}}else{console.log('parece undefined')};var incluyeFinde='b2c';var date1=utag_data.booking.checkIn.split("/").reverse().join("-");var date2=utag_data.booking.checkOut.split("/").reverse().join("-");function isWeekend(date1,date2){var d1=new Date(date1),d2=new Date(date2),isWeekend=false;while(d1<d2){var day=d1.getDay();isWeekend=(day==5)||(day==6);if(isWeekend){return true;}
d1.setDate(d1.getDate()+1);}
return false;}
if(date1&&date2&&isWeekend(date1,date2)){incluyeFinde='B2C';}else{incluyeFinde='B2B';};var childrenNumber='';if(utag_data.booking.childrenNumber&&(parseInt(utag_data.booking.childrenNumber))>0){childrenNumber='kids';}else if(utag_data.booking.childrenNumber&&(parseInt(utag_data.booking.childrenNumber))==0){childrenNumber='no_kids';}
gtagSales('NH_Pr0+transactions',childrenNumber,incluyeFinde,marcaDominio);}
}};utag.o[loader].loader.LOAD(id);})("497","nh-hoteles.es-main-2014");}catch(error){utag.DB(error);}
