//tealium universal tag - utag.496 ut4.0.201909201100, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
try{window.getCookie=function(c_name){var c_value=document.cookie;var c_start=c_value.indexOf(" "+c_name+"=");if(c_start==-1){c_start=c_value.indexOf(c_name+"=");}
if(c_start==-1){c_value=null;}else{c_start=c_value.indexOf("=",c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1){c_end=c_value.length;}
c_value=unescape(c_value.substring(c_start,c_end));}
return c_value;}
function lanzarTradeDoubler(){var dmy=utag_data.booking.checkOut.split("/");var validON="";var joindate=new Date(parseInt(dmy[2],10),parseInt(dmy[1],10)-1,parseInt(dmy[0],10));joindate.setDate(joindate.getDate()+21);validON=("0"+joindate.getFullYear()).slice(-4)+"-"+("0"+(joindate.getMonth()+1)).slice(-2)+"-"+("0"+(joindate.getDate()+1)).slice(-2);var precioTotal=parseFloat(utag_data.revenue);var order_id=utag_data.resId;var id_hotel=utag_data.products_id;(new Image()).src='https://tbs.tradedoubler.com/report?organization=1344402&event=152378&orderNumber='+order_id+'&orderValue='+precioTotal+'&epi='+id_hotel+'&validOn='+validON+'&currency=EUR';}
if(document.domain.match(/nh-hotel.?s\.(de|es|com(?!\.))/ig)>-1&&document.location.pathname.search(/booking\/(hotel.?s|step1-rates|step2-personal-data)/ig)>-1&&getCookie('subafCookie')!='2969017'&&getCookie('subafCookie')!='2939579'&&b['user.LoginState']=='not_logged'&&b['businessType']!='event'){jQuery.getScript('//www.123compare.me/widgets/CompareMeInit.js',()=>CompareMeInit.Init(2));}
if(document.location.href.search(/booking\/confirmation/ig)>-1&&getCookie('subafCookie')!=null&&document.domain.search(/nh-hotel.?s\.(de|es|com)/ig)>-1){if((getCookie('cartAbandonment123')!=null||getCookie('cartAbandonment123Continue')!=null)&&getCookie('cartAbandonment123CloseButton')==null&&getCookie('cartAbandonment123CloseBackground')==null&&b['user.LoginState']=='not_logged'&&b['businessType']!='event'){lanzarTradeDoubler();}}}catch(e){console.log('Unable fire affiliate pixels: '+e)}
}};utag.o[loader].loader.LOAD(id);})("496","nh-hoteles.es-main-2014");}catch(error){utag.DB(error);}
