//tealium universal tag - utag.493 ut4.0.201908290855, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.setCookie=function(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toGMTString();document.cookie=cname+"="+cvalue+";secure; "+expires+"; path=/";}
window.getCookie=function(c_name){var c_value=document.cookie;var c_start=c_value.indexOf(" "+c_name+"=");if(c_start==-1){c_start=c_value.indexOf(c_name+"=");}
if(c_start==-1){c_value=null;}else{c_start=c_value.indexOf("=",c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1){c_end=c_value.length;}
c_value=unescape(c_value.substring(c_start,c_end));}
return c_value;}
function deleteCookie(name){document.cookie='roundcube_sessauth'+'=; expires=Thu, 01-Jan-70 00:00:01 GMT;';}
function getRandomArbitrary(min,max){return Math.random()*(max-min)+min;}
function toDateFormat(date){return date[6]+date[7]+date[8]+date[9]+"-"+date[3]+date[4]+"-"+date[0]+date[1];}
function getDevice(){if(navigator.userAgent.match(/Tablet|iPad|tablet/i))
{return"tablet";}else if(navigator.userAgent.match(/Mobile|Windows Phone|Lumia|Android|webOS|iPhone|iPod|Blackberry|PlayBook|BB10|Opera Mini|\bCrMo\/|Opera Mobi/i))
{return"mobile";}else{return"desktop";}}
function calcularDiasEstancia(){var anoOut=utag.data.booking.checkOut.split('/')[2];var anoIn=utag.data.booking.checkIn.split('/')[2];var mesOut=utag.data.booking.checkOut.split('/')[1];var mesIn=utag.data.booking.checkIn.split('/')[1];var diaOut=utag.data.booking.checkOut.split('/')[0];var diaIn=utag.data.booking.checkIn.split('/')[0];var dias='';function diasMesIn(a){if(a.search(/01|03|05|07|08|10|12/g)>-1)return 31;else if(a.search(/02/g)>-1)return 28;else return 30;}
function calcularDias(){var diasPrimerMes=diasMesIn(mesIn)-Number(diaIn);return diasPrimerMes+Number(diaOut);}
if((anoOut>anoIn)||(mesOut>mesIn)){dias=calcularDias();}
else dias=Number(diaOut)-Number(diaIn);return dias;}
function getParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,'\\$&');var regex=new RegExp('[?&]'+name+'(=([^&#]*)|&|#|$)'),results=regex.exec(url);if(!results)return null;if(!results[2])return'';return decodeURIComponent(results[2].replace(/\+/g,' '));}
function fireKayakPixel(clickIdParam){var rndTck=getRandomArbitrary(1000000,9999999).toFixed(2);(new Image()).src="//www.kayak.com/s/kayakpixel/confirm/NHHOTELES?price="+utag.data.revenue+"&currency="+utag.data.currency+"&confirmation="+utag.data.id+"&clickId="+clickIdParam+"&rand="+rndTck+"";}
function fireTripadvisorPixel(refIdParam){var importeTrip=parseInt(utag_data.revenue*100);(new Image()).src="//www.tamgrt.com/RT?id=415631416&event=BOOKING_CONFIRMATION&partner=NHHotels1&refid="+refIdParam+"&gbv="+importeTrip+"&currency="+utag.data.currency+"&order_id="+utag.data.id+"&hotel_code="+utag.data.products_id[0]+"";}
function fireTrivagoPixel(){(new Image()).src="//secde.trivago.com/page_check.php?pagetype=track&ref="+utag.data.brandTrivago+"&hotel="+utag.data.products_id+"&arrival="+(new Date(utag_data.booking.checkIn.split("/").reverse().join("-")).getTime()/1000)+"&departure="+(new Date(utag_data.booking.checkOut.split("/").reverse().join("-")).getTime()/1000)+"&volume="+(Number(utag_data.revenue)+Number(utag_data.tax)+"")+"&booking_id="+utag.data.id+"&currency="+utag.data.currency;}
function fireGoogleHotelAdsPixel(){var dateFormat='%d/%m/%Y';(new Image()).src="//www.googletraveladservices.com/travel/clk/pagead/conversion/222/?label=HPA&guid=ON&script=0&ord="+Number((getRandomArbitrary(1000000,9999999)*1000000000).toFixed(0))+"&data=hct_partner_hotel_id="+utag.data.products_id+";hct_base_price="+Number(utag.data.revenue).toFixed(2)+";hct_total_price="+(Number(utag.data.tax)+Number(utag.data.revenue)).toFixed(2)+";hct_currency_code="+utag.data.currency+";hct_checkin_date="+utag.data.booking.checkIn+";hct_checkout_date="+utag.data.booking.checkOut+";hct_length_of_stay="+calcularDiasEstancia()+";hct_date_format="+dateFormat+";hct_booking_xref="+md5(utag.data.id)+";hct_ver=1.0.i";}
function fireGoogleHotelAdsPixelITPV2(){var tckScript=document.createElement('script');tckScript.type='text/javascript';tckScript.async=true;tckScript.src='https://www.googletagmanager.com/gtag/js?id=AW-1044818160';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(tckScript,s);var fechaOldIn=utag_data.booking.checkIn.split('/');var fechaNewIn=fechaOldIn[2]+'-'+fechaOldIn[1]+'-'+fechaOldIn[0];var fechaOldOut=utag_data.booking.checkOut.split('/');var fechaNewOut=fechaOldOut[2]+'-'+fechaOldOut[1]+'-'+fechaOldOut[0];window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1044818160');gtag('config','HA-222',{'conversion_cookie_prefix ':'_ha'});gtag('config','DC-4522553');gtag('event','purchase',{'send_to':['AW-1044818160/GBtfCJXTvYgBEPDRmvID','HA-222'],'transaction_id':md5(utag_data.id),'value':(Number(utag_data.revenue)).toFixed(2).toString(),'currency':utag_data.currency,'items':[{'id':utag_data.products_id[0],'start_date':fechaNewIn,'end_date':fechaNewOut,}]});}
function fireDerbysoftPixel(){(new Image()).src='//linkcenterus.derbysoftca.com/dplatform-linkcenter/trackBooking?accountCode=nhhotels&bookingNo='+utag.data.id+'&channelCode=&hotelCode='+utag.data.products_id[0]+'&roomTypeName=&roomTypeCode='+utag_data['booking.roomType'].replace("|",";")+'&ratePlanName=&ratePlanCode='+utag.data['booking.rate']+'&checkInDate='+toDateFormat(utag.data['booking.checkIn'])+'&checkOutDate='+toDateFormat(utag.data['booking.checkOut'])+'&guests='+(parseInt(utag.data['booking.adultsNumber'])+parseInt(utag.data['booking.childrenNumber'])+"")+'&rooms='+utag.data["booking.roomNumber"]+'&pureAmount='+utag.data.revenue+'&totalAmount='+(Number(utag_data.revenue)+Number(utag_data.tax)+"")+'&currency='+utag.data.currency+'&device='+getDevice()+'&channelSite=';}
if(document.location.href.search(/campid=([0-9]+)/ig)>-1){var campID=getParameterByName('campid')
var clickIDqsp='';var refIDqsp='';if(getParameterByName('clickId')!=null)clickIDqsp=getParameterByName('clickId');if(getParameterByName('refid')!=null)refIDqsp=getParameterByName('refid');var kayakID='';var tripadvID='';var trivagoID='';var ghadsID='';if(getCookie('campidCookieTCK')==null||getCookie('campidCookieTCK'==''))setCookie('campidCookieTCK','kayak:campid:clickid|tripadv:campid:refid|trivago:campid|ghads:campid',90);var cookie=getCookie('campidCookieTCK');kayakID=cookie.split('|')[0];tripadvID=cookie.split('|')[1];trivagoID=cookie.split('|')[2];ghadsID=cookie.split('|')[3];switch(campID){case'8432193':kayakID=kayakID.split(':')[0]+':'+campID+':'+clickIDqsp;break;case'8435709':tripadvID=tripadvID.split(':')[0]+':'+campID+':'+refIDqsp;break;case'8431996':trivagoID=trivagoID.split(':')[0]+':'+campID;break;case'8565112':ghadsID=ghadsID.split(':')[0]+':'+campID;break;}
setCookie('campidCookieTCK',kayakID+'|'+tripadvID+'|'+trivagoID+'|'+ghadsID,90);}
if(document.location.href.search(/booking\/confirmation/ig)>-1){var campidCookieTCKFire=getCookie('campidCookieTCK');var readKayak=campidCookieTCKFire.split('|')[0];if(readKayak.split(':')[1]!='campid')fireKayakPixel(readKayak.split(':')[2]);var readTripadv=campidCookieTCKFire.split('|')[1];if(readTripadv.split(':')[1]!='campid')fireTripadvisorPixel(readTripadv.split(':')[2]);var readTrivago=campidCookieTCKFire.split('|')[2];if(readTrivago.split(':')[1]!='campid')fireTrivagoPixel();var readGhads=campidCookieTCKFire.split('|')[3];if(readGhads.split(':')[1]!='campid'){fireGoogleHotelAdsPixel();fireGoogleHotelAdsPixelITPV2();}
if(campidCookieTCKFire.search(/8432193|8435709|8431996/g)>-1)fireDerbysoftPixel();deleteCookie('campidCookieTCK');}
}};utag.o[loader].loader.LOAD(id);})("493","nh-hoteles.es-main-2014");}catch(error){utag.DB(error);}
